title:              SKUP
email:              info@skup.be
description:        Een SketchUp blog
author:             Johan Van Mol
baseurl:            
url:                "https://vibrant-ramanujan-62b820.netlify.com/"
permalink:          /:title.html

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site